CREATE TABLE user (
    user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    account_type VARCHAR(50) NOT NULL
);

CREATE TABLE company (
    company_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    owner BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL
)

CREATE TABLE schedule (
    schedule_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    create_datetime DATETIME DEFAULT CURRENT_TIMESTAMP
)